spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fresh?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: a
   http:
      encoding:
         force: true
         charset: utf-8
         enabled: true

   session:
      store-type: redis
   redis:
      datasource: 0
      host: 127.0.0.1
      port: 6379
      password: null
      timeout: 5000
      jedis:
         pool:
            max-active: 0
   mail:
      host: smtp.163.com
      username: s1076748669@163.com
      password: BSHFNMOVDLBOUIYB
      port: 465
      protocol: smtp
      properties:
         mail:
            smtp:
               auth: true
               ssl:
                  enabled: true


#mybatis配置
mybatis:
   mapper-locations: mapper/*Mapper.xml
   type-aliasses-package: com.sun.fresh.goods.entity
   
eureka:
   clinet:
      service-url:
         defaultZone: http://sun:123456@127.0.0.1:6868/eureka